# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warehouse.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\x12\twarehouse\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1c\n\x0egetDataRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\xff\x01\n\rWarehouseData\x12\x1e\n\x16warehouseApplicationID\x18\x01 \x01(\t\x12\x13\n\x0bwarehouseID\x18\x02 \x01(\t\x12\x15\n\rwarehouseName\x18\x03 \x01(\t\x12\x18\n\x10warehouseAddress\x18\x04 \x01(\t\x12\x1b\n\x13warehousePostalCode\x18\x05 \x01(\t\x12\x15\n\rwarehouseCity\x18\x06 \x01(\t\x12\x18\n\x10warehouseCountry\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\x12\'\n\x0bproductData\x18\t \x03(\x0b\x32\x12.warehouse.Product\"x\n\x07Product\x12\x11\n\tproductID\x18\x01 \x01(\t\x12\x13\n\x0bproductName\x18\x02 \x01(\t\x12\x17\n\x0fproductCategory\x18\x03 \x01(\t\x12\x17\n\x0fproductQuantity\x18\x04 \x01(\x05\x12\x13\n\x0bproductUnit\x18\x05 \x01(\t2R\n\tWarehouse\x12\x45\n\x0cgetDataForID\x12\x19.warehouse.getDataRequest\x1a\x18.warehouse.WarehouseData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETDATAREQUEST']._serialized_start=63
  _globals['_GETDATAREQUEST']._serialized_end=91
  _globals['_WAREHOUSEDATA']._serialized_start=94
  _globals['_WAREHOUSEDATA']._serialized_end=349
  _globals['_PRODUCT']._serialized_start=351
  _globals['_PRODUCT']._serialized_end=471
  _globals['_WAREHOUSE']._serialized_start=473
  _globals['_WAREHOUSE']._serialized_end=555
# @@protoc_insertion_point(module_scope)
