# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import warehouse_pb2 as warehouse__pb2


class WarehouseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getDataForID = channel.unary_unary(
                '/warehouse.Warehouse/getDataForID',
                request_serializer=warehouse__pb2.getDataRequest.SerializeToString,
                response_deserializer=warehouse__pb2.WarehouseData.FromString,
                )


class WarehouseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getDataForID(self, request, context):
        """gets the data for a warehouseID (not warehouseApplicationID)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WarehouseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getDataForID': grpc.unary_unary_rpc_method_handler(
                    servicer.getDataForID,
                    request_deserializer=warehouse__pb2.getDataRequest.FromString,
                    response_serializer=warehouse__pb2.WarehouseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'warehouse.Warehouse', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Warehouse(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getDataForID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/warehouse.Warehouse/getDataForID',
            warehouse__pb2.getDataRequest.SerializeToString,
            warehouse__pb2.WarehouseData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
